### ISSUE TITLE
静态资源返回404

### ISSUE THREAD

**Issue by daniel-007** [insionng/macross#1]
配置：v.Use(static.Static("static"))，并创建与templates平级目录static，请问如何访问js，css等资源？

**Comment by insionng** [comment]
@daniel-007 感谢报告问题，这个是静态中间件的BUG，我会尽快修复。你可以先用以下方式：
```
// ...
// 放在最后一个路由之后
// 
v.Static("/", "static")
v.Run(":7000")
```

**Comment by insionng** [comment]
@daniel-007 静态中间件已经修正，另外这里有一个能够工作的示例：https://github.com/macross-contrib/vuejsto

**Comment by daniel-007** [comment]
@insionng 好的，感谢回复。
